kind: Deployment
apiVersion: apps/v1
metadata:
  name: dhalion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhalion
  template:
    metadata:
      labels:
        app: dhalion
    spec:
      containers:
      - name: python-container
        image: 9923/dhalion:4
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /usr/src/app/test-pd
          name: test-volume
        env:
        - name: AVG_OVER_TIME
          value: "1m"
        - name: COOLDOWN
          value: "240"  
        - name: MIN_REPLICAS
          value: "1"
        - name: MAX_REPLICAS
          value: "5" 
        - name: SLEEP_TIME
          value: "10"
        - name: BACKPRESSURE_LOWER_THRESHOLD
          value: "200"
        - name: BACKPRESSURE_UPPER_THRESHOLD
          value: "500"
        - name: DERIV_CONSUMER_LAG_THRESHOLD
          value: "1000"
      volumes:
      - name: test-volume
        hostPath:
          # directory location on host
          path: /host_mnt/c/temp/soccerdb-pv
          # this field is optional
          type: DirectoryOrCreate 
            # ports:
        # - containerPort: 9092
        # - containerPort: 7071
      
