apiVersion: v1
data:
  config.yaml: |
    rules:      
    - seriesQuery: 'flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max{kubernetes_namespace!="",kubernetes_pod_name!=""}'
      name: {as: "lag_rate"}
      resources:
        overrides:
          kubernetes_namespace: {resource: "namespace"}
          kubernetes_pod_name: {resource: "pod"}
      metricsQuery: '((sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max) by (<<.GroupBy>>) - 1000000) / abs(sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max) by (<<.GroupBy>>) - 1000000))* (1 + (deriv(sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max) by (<<.GroupBy>>)[5m:10s]) / sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_consumed_rate) by (<<.GroupBy>>)))'  
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: my-release
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-adapter
    app.kubernetes.io/part-of: prometheus-adapter
    app.kubernetes.io/version: v0.9.1
    helm.sh/chart: prometheus-adapter-3.0.0
  name: my-release-prometheus-adapter2
  namespace: default
