apiVersion: custompodautoscaler.com/v1
kind: CustomPodAutoscaler
metadata:
  name: simple-pod-metrics-python
spec:
  template:
    spec:
      containers:
      - name: simple-pod-metrics-python
        image: 9923/custom-autoscaler-test:18
        imagePullPolicy: IfNotPresent
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flink-taskmanager
  config:
    - name: interval
      value: "10000"
    - name: downscaleStabilization
      value: "60"
    - name: upscaleStabilization
      value: "60"

