apiVersion: custompodautoscaler.com/v1
kind: CustomPodAutoscaler
metadata:
  name: simple-pod-metrics-python
spec:
  template:
    spec:
      containers:
      - name: simple-pod-metrics-python
        imager-test:5: 9923/custom-autoscale
        imagePullPolicy: IfNotPresent
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flink-taskmanager
  config:
    - name: interval
      value: "10000"
