apiVersion: v1
data:
  config.yaml: |
    rules:      
    - seriesQuery: 'deriv(flink_jobmanager_numRegisteredTaskManagers[5m])'
      seriesFilters:
      - is: ".*flink_jobmanager_numRegisteredTaskManagers.*"
      name: {as: "previous-scaledown"}
      resources:
        overrides:
          kubernetes_namespace: {resource: "namespace"}
          kubernetes_pod_name: {resource: "pod"}
      metricsQuery: 'deriv(flink_jobmanager_numRegisteredTaskManagers[5m])'    
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: my-release
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-adapter
    app.kubernetes.io/part-of: prometheus-adapter
    app.kubernetes.io/version: v0.9.1
    helm.sh/chart: prometheus-adapter-3.0.0
  name: my-release-prometheus-adapter2
  namespace: default
