apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: flink-taskmanager
  namespace: default
spec:
  maxReplicas: 8
  minReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flink-taskmanager
behavior:
  scaleDown:
    stabilizationWindowSeconds: 300
  scaleUp:
    stabilizationWindowSeconds: 150
