apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: flink-taskmanager
  namespace: default
spec:
  maxReplicas: 5
  minReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flink-taskmanager
  targetCPUUtilizationPercentage: 60