apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  type: LoadBalancer
  selector:
    app: kafka
  ports:
    - port: 9094
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 3
  serviceName: kafka
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      annotations:
        prometheus.io/port: '7071'
        ververica.com/scrape_every_2s: 'true'
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: 9923/kafka_jmx:4
          imagePullPolicy: Always
          ports:
            - containerPort: 9094
            - containerPort: 7071
          env:
            - name: HOSTNAME_COMMAND
              value: "echo \"$HOSTNAME.kafka.vas-kafka-stg\""
            - name: BROKER_ID_COMMAND
              value: "hostname | awk -F'-' '{print $2}'"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zoo1:2181
            - name: KAFKA_LISTENERS
              value: "INSIDE://:9092,OUTSIDE://:9094"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INSIDE"
            - name: KAFKA_PORT
              value: "9092"
            - name: KAFKA_CREATE_TOPICS
              value: topic:20:1
            - name: EXTRA_ARGS 
              value: -javaagent:/usr/app/jmx_prometheus_javaagent.jar=7071:/usr/app/prom-jmx-agent-config.yml

